name = "Float"
description = "An elegant blog theme"
license = "MIT"
homepage = "https://float-theme.netlify.app/"
# The minimum version of Zola required
min_version = "0.11.0"

# Any variable there can be overriden in the end user `config.toml`
# You don't need to prefix variables by the theme name but as this will
# be merged with user data, some kind of prefix or nesting is preferable
# Use snake_casing to be consistent with the rest of Zola
[extra]
google_analytics = false
# google_analytics_id = "UA-286354-4"

google_adsense = false
# google_adsense_id = "ca-pub-8948136958888709"

# twitter_account = "@LeonH"

likecoin = false
# likecoin_name = "leon0824"

utterances = false
# utterances_repo = "uniuni-space/exp2.uniuni.space"

# The theme author info: you!
[author]
name = "Leon"
homepage = "https://exp2.uniuni.space/"
